import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  drawerBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.2)",
    zIndex: 20,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    display: "flex",
  },
  drawerContent: {
    width: 220,
    height: "100%",
    backgroundColor: "#fff",
    paddingTop: 60,
    paddingHorizontal: 20,
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    alignItems: "flex-start",
  },
  drawerButton: {
    backgroundColor: "#eaf3ff",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginVertical: 10,
    alignItems: "center",
    width: "100%",
  },
  drawerButtonText: {
    color: "#2870e0",
    fontWeight: "bold",
    fontSize: 18,
    letterSpacing: 1,
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.3)",
    zIndex: 10,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    minWidth: 260,
    maxWidth: "80%",
  },
  botPickerRow: {
    flexDirection: "row",
    marginBottom: 16,
    justifyContent: "center",
  },
  bubbleButton: {
    backgroundColor: "#fff",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 28,
    marginHorizontal: 6,
    marginVertical: 6,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    borderWidth: 2,
    borderColor: "#eee",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 60,
  },
  bubbleButtonActive: {
    borderColor: "#2870e0",
    backgroundColor: "#eaf3ff",
  },
  bubbleButtonText: {
    color: "#2870e0",
    fontWeight: "bold",
    fontSize: 18,
    letterSpacing: 1,
  },
  bubbleButtonTextActive: {
    color: "#174080",
  },
  logoFull: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 0,
  },
  logoFallbackFull: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 0,
  },
  overlay: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    backgroundColor: "rgba(40, 80, 160, 0.25)", // blue tint, less opacity
  },
  menu: {
    alignItems: "center",
    marginTop: 20,
  },
  menuSubtitle: {
    fontSize: 18,
    marginBottom: 16,
  },
  logo: {
    width: 200,
    height: 200,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#333",
    backgroundColor: "#fff",
    borderRadius: 16,
  },
  logoFallback: {
    width: 200,
    height: 200,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#333",
    backgroundColor: "#fff",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  logoFallbackText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#333",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
  human: {
    color: "blue",
    fontSize: 18,
    margin: 5,
  },
  bot: {
    color: "green",
    fontSize: 18,
    margin: 5,
  },
  gameOver: {
    fontSize: 22,
    color: "red",
    margin: 15,
  },
});

export default styles;
